lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false      # Set to 'true' if using simulation time.
    autostart: true          # Automatically configure and activate managed nodes.
    bond_timeout: 5.0         # Timeout for bond establishment.
    node_names:              # List all nodes to be managed in order of dependency:

      - planner_server      # Requires localization and a map to compute plans.
      - smoother_server     # Depends on planner_server to smooth the global plan.
      - waypoint_follower   # Executes waypoints; depends on smoother_server.
      - behavior_server     # Executes behaviors; relies on planner_server outputs.
      - collision_monitor   # Requires costmaps, ensuring obstacles are tracked.
      - controller_server   # Depends on localization (slam_toolbox) and costmaps.
      - velocity_smoother   # Fine-tunes motion commands; safe to run last.
      - bt_navigator      # Executes the behavior tree; needs planner_server and smoother_server.
     # - local_costmap/local_costmap
      #- global_costmap/global_costmap