slam_toolbox:
  ros__parameters:

    # Plugin params (using defaults from reference)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    # Mode can be "sync" or "async" for synchronous and asynchronous SLAM.
    mode: mapping
    debug_logging: true  # Set to true for verbose logging.
    odom_frame: odom  # The frame ID for the odometry data.
    base_frame: base_link  # The frame ID for the robot's base.
    map_frame: map  # The frame ID for the map.
    scan_topic: /scan  # The topic for the LiDAR scan data.
    # The resolution (in meters) of the output map.
    resolution: 0.03

    # How often to publish the map (in seconds).
    map_update_intervale: 0.5
    throttle_scans: 2


    # How often the transform is published.
    transform_publish_period: 0.05
    minimum_travel_distance: 0.0  # Minimum distance to travel before updating the map.
    # Scan parameters
    max_laser_range: 12.0          # Maximum range of your LiDAR.
    min_laser_range: 0.1           # Minimum range threshold to consider.
    minimum_time_interval: 0.1    # Minimum time interval between scans.
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    scan_buffer_size: 1000
    scan_buffer_maximum_scan_distance: 12.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - For scan matching and loop closure
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - For Loop Closure
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1